In [ ]:
# 주피터노트북 셀 스타일 조절
from IPython.core.display import display, HTML
# display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고메시지 숨기기
# import warnings\
# warnings.filterwarnings(action='ignore')

## Numpy 개요
* Numeric + Python = Numpy
* 수학 및 과학 연산을 위한 파이썬 패키지
* 배열이나 행렬 계산에 용이한 메서드를 제공
* 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함

* 관련 사이트 : http://www.numpy.org

* 일반 List에 비해 빠르고, 메모리 효율적
* 반복문 없이 데이터 배열에 대한 처리를 지원함
* 선형대수와 관련된 다양한 기능을 제공함
* Reference Site
* cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
* https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
* 데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS

In [2]:
import numpy as np
np.__version__

'1.24.3'

## 넘파이 배열 이해하기

## ndim(dimention, rank)
* 몇 차원인지 반환

In [4]:
a = np.array(0) #array 매서드를 통해 0을 넣어 array라는 자료 구조가 됐다
a, a.ndim, type(a) #a.ndim = 차원

(array(0), 0, numpy.ndarray)

In [6]:
a = np.array([2, 3, 4])
a, a.ndim, type(a)

(array([2, 3, 4]), 1, numpy.ndarray)

In [10]:
a = [[2, 3, 4], [3,4,5]]
a

[[2, 3, 4], [3, 4, 5]]

In [8]:
a = np.array([[2, 3, 4], [3,4,5]]) # 차원 계산 시 대괄호가 몇갠지 보면 됨
a, a.ndim, type(a)

(array([[2, 3, 4],
        [3, 4, 5]]),
 2,
 numpy.ndarray)

In [11]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] ) #3차원
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [12]:
a.shape

(2, 2, 3)

## shape
* 행렬의 차원으로, 몇행 몇열인지 반환
* 아래의 경우 1차원에 4, 2차원에 2로 (4,2)로 표현됨

In [ ]:
a.shape?

In [13]:
a = np.array(3)
a, a.shape # 행렬아니라 안찍힘

(array(3), ())

In [14]:
a = np.array([ 1, 3, 5, 7, 9 ]) #1차원
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [15]:
a = np.array([[1,2,3], [4,5,6]]) #2차원
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [16]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## size
* 요소의 수 (차원과 무관)

In [17]:
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [18]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

## 넘파이 배열
* 리스트를 넘파이 배열로 생성 np.array(리스트)
* 관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [19]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44] #임의의 리스트
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [21]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5


In [24]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)})')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5)


In [25]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [28]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [30]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [31]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21) #행렬이 아니라서 차원 구조 성립 안됨
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
* 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
* 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
* 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [2]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 실제 숫자 연산 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [34]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 리스트 간 곱셈 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [35]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2) # 각 요소마다 연선이 들어감 (엘리먼트 와이즈)

[3 4 5]
[2 4 6]


In [36]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype
* int가 더 세밀해졌다!

In [5]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [12]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [13]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN

* 넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
* 다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [3]:
np.array([0, 1, -1, 0]) / np.array([0, 0, 0, 0])

C:\Users\limfl\AppData\Local\Temp\ipykernel_948\1470919378.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([0, 0, 0, 0])
C:\Users\limfl\AppData\Local\Temp\ipykernel_948\1470919378.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([0, 0, 0, 0])


array([ nan,  inf, -inf,  nan])

In [5]:
np.log(0)

C:\Users\limfl\AppData\Local\Temp\ipykernel_948\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [6]:
np.exp(-np.inf)

0.0

## 기술통계

In [7]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [8]:
# 평균
np.mean(x)

4.8076923076923075

In [9]:
# 분산
np.var(x)

115.23224852071006

In [10]:
# 표준편차
np.std(x)

10.734628476137871

In [11]:
# 최댓값
np.max(x)

23

In [12]:
# 최소값
np.min(x)

-24

In [14]:
# 중앙값
np.median(x)

5.0

### 사분위수
* 사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
* 박스플롯

In [16]:
# 최소값
np.percentile(x, 0)

-24.0

In [17]:
# 1사분위수
np.percentile(x, 25)

0.0

In [18]:
# 2사분위수
np.percentile(x, 50)

5.0

In [19]:
# 3사분위수
np.percentile(x, 75)

10.0

In [20]:
# 최댓값
np.percentile(x, 100)

23.0

## 넘파이 함수로 배열 만들기

In [21]:
# 넘파이 함수로 배열을 만들때에는 디폴트가 실수형 - 정보를 걸러내기 위해
print(np.ones(10), np.ones(10).dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [22]:
# 2행 4열 - 튜플로
print(np.ones((2, 4)), np.ones((2, 4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [23]:
# 타입 지정
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [24]:
print(np.zeros(10), np.zeros(10).dtype) #정보를 날릴 떄, 무의미한 공간을 채울 때

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [25]:
# 3행 3열 - 튜플로
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [26]:
# empty - 메모리가 비어있음 -> 메모리 초기화 X 
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int)) # 기존 메모리에 있던 값을 출력 (정확히 알 수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[      0       1       0]
 [5570652    1548       0]
 [    768     571 7077990]]


In [27]:
# 리스트 +  레인지

print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [28]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [29]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [30]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수 #분할 

array([  0.,  25.,  50.,  75., 100.])

In [31]:
# logspace
np.logspace(0.1, 1, 10) #로그값 

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열
* reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [33]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [35]:
arr = arr.reshape(10,5) # 10행 5열로 재배열
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [38]:
arr2 = arr.reshape(5,10) # 10행 5열을 5행 10열로
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [39]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [40]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [42]:
print(np.arange(2, 101, 2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [45]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape #열이 생겼으니 2차원

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [51]:
# 1-20까지 배열을 만들고 모형을 5행 4열로
a = np.arange(1,21).reshape(5,4)
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 2,
 (5, 4))

In [52]:
# 5열의 모형으로
a.reshape(-1, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [55]:
# 사이즈가 맞아야 한다.
np.arange(1, 21).reshape(-1, 7)

ValueError: cannot reshape array of size 20 into shape (7)

In [61]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [62]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [63]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [64]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [65]:
# -1 하나만 넣으면 flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

## 넘파이배열의 자료형 형변환
* 배열명2 = 배열명1.astype(자료형)
* 자료형 = np.float64, np.int32


In [67]:
matrix1 = np.arange(1,10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [71]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [74]:
# 문자열형, 3행 3열 -> 불가 str 이라고 표시 안해서
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtype[str_]'>.

In [73]:
# 정수형 => 문자열 U5
matrix.astype('<U5')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U5')

In [75]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [76]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [77]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [78]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [79]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [80]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

## 넘파이 배열의 인덱싱
* 넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

### 1D array

In [81]:
a = np.array([1,3,5,7,9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [82]:
a[0]

1

In [83]:
a[2]

5

In [86]:
a[-1] # 맨 뒤

9

In [85]:
a[-3]

5

In [87]:
a[-5]

1

In [88]:
# 복수 가능
a[[0, 2, 4]]

array([1, 5, 9])

In [90]:
a

array([1, 3, 5, 7, 9])

In [92]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array([[1,3], [4,2]]) #2차원
b

array([[1, 3],
       [4, 2]])

In [95]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[b] # 넣는 값은 인덱싱 값으로 인식

array([[3, 7],
       [9, 5]])

In [97]:
# 값 수정
a[2] = 0
a

array([1, 3, 0, 7, 9])

In [98]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [99]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

### 2D array


In [100]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [101]:
# 2차원 인덱싱할 때, 값을 하나만 넣으면 행인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [103]:
a[1]

array([5, 6, 7, 8, 9])

In [102]:
a[2]

array([10, 11, 12, 13, 14])

In [104]:
a[-1]

array([10, 11, 12, 13, 14])

In [105]:
a[-2]

array([5, 6, 7, 8, 9])

In [107]:
# 차원 인덱싱
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
# 값이 2개 들어가면 행/열 인덱싱
a[0,0] #0번째행에 0

0

In [109]:
a[0,1]

1

In [110]:
a[0,2]

2

In [111]:
a[1,0]

5

In [112]:
a[1,2]

7

In [113]:
# 값 수정
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [114]:
a[-1] = [10] # -1행을 10으로 채워
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 10, 10, 10, 10]])

In [117]:
a[0] += 1, 2, 3, 4, 5
a

array([[ 3,  7, 11, 15, 19],
       [ 5,  6,  7,  8,  9],
       [10, 10, 10, 10, 10]])

In [118]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [119]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [120]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0]

0

In [122]:
matrix_b[0][0] #추출해서 또 추출(2차원이라 가능)

0

In [123]:
# 2차원 마지막행 마지막열 -> 3행 4열
matrix_b[-1,-1]

11

In [124]:
matrix_b[2][3]

11

In [125]:
matrix_b[2,0] =100
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

## 넘파이배열 슬라이싱

In [126]:
# 1차원

a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [127]:
a[:]

array([1, 3, 5, 7, 9])

In [128]:
a[1:]

array([3, 5, 7, 9])

In [129]:
a[-1:]

array([9])

In [130]:
a[:3]

array([1, 3, 5])

In [131]:
a[:-1]

array([1, 3, 5, 7])

In [132]:
a[1:4]

array([3, 5, 7])

In [133]:
a[1:-1]

array([3, 5, 7])

In [134]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
a[::2] #스텝

array([0, 2, 4, 6, 8])

In [137]:
a[::5]

array([0, 5])

In [138]:
a[::-1] #역순

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [142]:
a[1::2] # 홀수만

array([1, 3, 5, 7, 9])

In [143]:
a[:-2:2]

array([0, 2, 4, 6])

In [144]:
a[2:-2:2]

array([2, 4, 6])

In [145]:
# 2차원

a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [146]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [147]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [148]:
a[3:]

array([], shape=(0, 5), dtype=int32)

In [149]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [150]:
a[-3:] # -3 = 0 행

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [152]:
a[:0] #마지막 인덱스는 -1 값 출력

array([], shape=(0, 5), dtype=int32)

In [153]:
a[:-1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [154]:
a[:-2]

array([[10, 11, 12, 13, 14]])

In [155]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [158]:
a[:2]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [159]:
a[:,:] #행에 대한 범위, 열에 대한 범위

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [160]:
a[:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [161]:
a[:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [162]:
a[:,-1:]

array([[14],
       [19],
       [24]])

In [163]:
a[:,-4:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [165]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [164]:
a[:,:1]

array([[10],
       [15],
       [20]])

In [167]:
a[:,:5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [168]:
a[:,:-1]

array([[10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [169]:
a[:,:-2]

array([[10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [170]:
a[:,0:1]

array([[10],
       [15],
       [20]])

In [171]:
a[:,2:3]

array([[12],
       [17],
       [22]])

In [172]:
a[:,1:-1]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [174]:
a = np.arange(10, 100).reshape(9,10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
a[2:5, :] #시작은 포함, 끝은 제외

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [177]:
a[:, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [178]:
a[2:5, 2:5]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [179]:
a[::2, ::2]

array([[10, 12, 14, 16, 18],
       [30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [181]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
a[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [183]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 numpy.ndarray,
 2)

### 전치행렬
* a의 각행을 열로 바꾼
* 넘파이배열.T : 행과 열 구조 변경

In [184]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [185]:
# 2행 3열로 변환 T
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [186]:
print(matrix_d.reshape(2,3)) #리쉐입은 한번 쭉 나열 후(플래튼) 구조 변경

[[1 2 3]
 [4 5 6]]


### 난수로 구성된 넘파이 배열
* np.random.randint(start, end, n) : 정수 난수
* np.random.randint(start, end, (i, j) 

In [ ]:
np.random?

In [188]:
# 1~10 사이의 숫자중에서 랜덤으로 10개 출력
np.random.randint(1, 10, 10)

array([9, 1, 8, 4, 1, 3, 4, 2, 7, 8])

In [189]:
# 2행 5열로 랜덤하게 츨력
np.random.randint(1, 10, (2,5))

array([[7, 2, 9, 8, 6],
       [1, 7, 2, 4, 1]])

### 섞기
np.random.shuffle(넘파이배열) 원본에 바로 적용

In [ ]:
np.random.shuffle?

In [190]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [191]:
np.random.shuffle(matrix_e)
matrix_e

array([ 4, 10,  3,  9,  2,  8,  7,  1,  5,  6])

In [199]:
# Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

np.random.randint(1, 46, 6)

array([42, 34, 28, 42, 35,  7])

In [200]:
num= np.arange(1,47)
np.random.shuffle(num)
num[:6]

array([ 4,  9, 41, 12, 39, 11])

### 실수 난수
np.random.randn(n) np.random.randn(i, j)

In [201]:
np.random.randn?

In [202]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1 **많이사용
matrix1

array([ 1.74158487,  0.86538833,  0.64886165,  0.00330931, -0.92354546,
       -0.44738542,  0.19466394, -0.82775202, -0.12988071,  0.24167518])

In [203]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-1.2862547 , -1.46972961, -0.82916837,  0.54874692],
       [ 0.95881989, -0.02195207, -0.28854837, -2.33990635],
       [-1.06887046, -1.37752151,  0.15757014, -1.05945409],
       [-0.33606096,  0.7377191 , -0.00751576, -0.94947016]])

In [204]:
matrix1.max(), matrix1.min()

(1.7415848721567797, -0.9235454612116828)

### 집계함수에서의 축
* 2차원에서의 집계합수(sum, mean)
* axis = 0, 1
* np.sum(넘파이배열, axis=0/1)
* np.mean(넘파이배열, axis=0/1)
* np.sort(넘파이배열, axis=0/1)

In [206]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[43,  7, 11, 38,  1],
       [47, 43, 44, 36,  6],
       [48, 34, 44, 20, 14],
       [16, 19, 25, 48, 13],
       [26, 47, 25, 25, 36]])

In [207]:
# 차원이 많을 때 어느 방향으로 무엇을 계산할지 알려줌 axis

np.sum(m1, axis=0) # (x)행 합계

array([180, 150, 149, 167,  70])

In [210]:
# 1번째 행의 합계
np.sum(m1[0,:], axis=0)

100

### np.sort() 오름차순 정렬

In [211]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[34, 14, 47],
       [41,  5, 46],
       [47, 37, 49],
       [49, 44, 26]])

In [213]:
np.sort(m2) # 각 행 안의 요소가 오름차순 정렬

array([[14, 34, 47],
       [ 5, 41, 46],
       [37, 47, 49],
       [26, 44, 49]])

In [212]:
np.sort(m2, axis=0) # 행방향(axis=0) 오름차순(요소별로)

array([[34,  5, 26],
       [41, 14, 46],
       [47, 37, 47],
       [49, 44, 49]])

In [214]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[49, 44, 26],
       [47, 37, 49],
       [41,  5, 46],
       [34, 14, 47]])

In [215]:
np.sort(m2, axis=1) # 열방향 오름차순

array([[14, 34, 47],
       [ 5, 41, 46],
       [37, 47, 49],
       [26, 44, 49]])

### 인덱스 소팅
* np.argsort(넘파이배열, axis=0,1)
* 정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [216]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [217]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

#### 넘파이 배열 요소 추가와 삭제

* 삽입
    * np.insert(배열, 위치인덱스, 값, axis=0/1)
    * 2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
* 삭제
    * np.delete(배열명, 위치인덱스, axis=0/1)

In [3]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# m3배열 0번 인덱스에 100을 넣자
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [10]:
m3[-1]

10

In [ ]:
np.insert?

In [11]:
# m3배열 -1번째 인덱스에 500 삽입
np.insert(m3, -1, 500) # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [12]:
np.insert(m3, len(m3), 500) # 끝에 삽입 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [13]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입(강제로 플래튼)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [15]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1) #열방향 0번째 인덱스에 삽입

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [16]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [30]:
print(m4)
m4.shape, m4.shape[1], len(m4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


((3, 3), 3, 3)

In [18]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [19]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [20]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

#### 배열 합치기
* np.vstack((배열1,배열2....)) : 세로 합치기
* np.hstack((배열1,배열2....)) : 가로 합치기
* np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# 세로 합치기
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# 가로 합치기
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [25]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [26]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [27]:
f = np.concatenate((c,d), axis=0) #행방향 합치기
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [28]:
f = np.concatenate((c,d), axis=1) #열방향 합치기
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

#### boolean indexing, mask
* 조건절의 결과는 True, False로 반환
* True인 결과의 데이터 반환
* 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [31]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
# 불린 - 조건절
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [33]:
# 불린 인덱싱
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
# 조건에 맞는 개수가 몇개인가 (t = 1, f = 0 활용)
(matrix > 10).sum()

10

Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [52]:
a = np.random.randint(1, 100, 30)
(a > 30) & (a < 70)

array([False, False, False,  True, False,  True, False,  True,  True,
        True, False, False,  True,  True, False, False, False,  True,
       False, False,  True, False, False,  True,  True, False, False,
        True, False, False])

In [55]:
a = np.random.randint(1, 100, 30)
a, a[(a > 30) & (a < 70)]

(array([37, 74, 51, 88, 18, 38,  9, 48, 12, 29, 63, 66, 50, 90, 35, 35, 79,
        15, 11, 52, 70, 28,  7, 51, 84,  6, 22, 47, 97,  4]),
 array([37, 51, 38, 48, 63, 66, 50, 35, 35, 52, 51, 47]))

In [59]:
# ~ 은 reverse를 의미
num = np.random.randint(1, 100, 30)
num[~(num > 30) & (num < 70)]

array([ 3, 29, 27, 30, 27, 11,  4,  3])

In [60]:
# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([ 3, 97,  4, 98,  3])

In [61]:
 num[~(num < 10) | (num > 90)]

array([45, 82, 29, 68, 27, 72, 68, 30, 48, 48, 61, 44, 46, 27, 11, 80, 59,
       46, 97, 79, 35, 67, 83, 98, 36, 76, 43])

#### fancy indexing(filtering)

In [63]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([90, 11, 46, 54, 49, 35, 22, 93, 24,  1, 31, 42, 38, 50, 91, 19, 60,
        11, 95, 89, 11, 85, 47,  9, 99, 75, 58, 97, 94, 37]),
 array([90, 46, 54, 31, 11]))

#### np.where()를 이용한 필터링 *많이사용
* np.where(조건식) : 조건식 만족하는 인덱스 반환
* np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
* 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [64]:
np.where?

In [65]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [66]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))